name: License Check

on:
  push:

jobs:
  license-check:
    name: License Check
    runs-on: ubuntu-latest
    env:
      MISE_PROFILE: cicd

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          version: 2025.6.8
          experimental: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache licensei
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .licensei.cache
          key: ${{ runner.os }}-licensei-${{ hashFiles('**/go.sum', '.licensei.toml') }}
          restore-keys: |
            ${{ runner.os }}-licensei-

      - name: Run License Check
        id: run-license-check
        run: |
          set -o pipefail
          {
            go mod vendor
            licensei cache --debug
            licensei check --debug
            licensei header --debug
          } | tee license-check.log
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload License Check Report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: license-check-report-ubuntu
          path: license-check.log
