name: License Check

on:
  push:

jobs:
  license-check:
    name: License Check
    runs-on: ubuntu-latest
    env:
      MISE_PROFILE: cicd

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2
        with:
          version: 2025.6.8
          experimental: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache licensei
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: .licensei.cache
          key: ${{ runner.os }}-licensei-${{ hashFiles('**/go.sum', '.licensei.toml') }}
          restore-keys: |
            ${{ runner.os }}-licensei-

      - name: Run License Check
        id: run-license-check
        run: |
          set -o pipefail
          {
            go mod vendor
            licensei cache --debug
            licensei check --debug
            licensei header --debug
          } | tee license-check.log
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload License Check Report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: license-check-report-ubuntu
          path: license-check.log
